version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Docker client
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-ce
      - run:
          name: Build Docker image
          command: docker build -t domvito55/kindderlogger:v1 .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
            docker push domvito55/kindderlogger:v1
      - run:
          name: Update ECS service
          command: |
            aws ecs update-service --cluster skillsCluster --service skillsService --force-new-deployment
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
